name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        #   user: __token__
        #   password: ${{ secrets.PYPI_API_TOKEN }}
